### ISSUE TITLE
add it to luarocks.org

### ISSUE THREAD

**Issue by teto** [Mic92/vicious#53]
I was going through the list of lua packages to update in https://github.com/NixOS/nixpkgs/pull/33903 and this one seems simple enough that I can convert it automatically from luarocks to a nix derivation. so adding it to luarocks could be nice.

**Comment by Mic92** [comment]
Can awesomeWM find packages installed with luarocks?

**Comment by psychon** [comment]
> Can awesomeWM find packages installed with luarocks? 

Commit 202be62157103c34fab12283fe8d6e46df615b67 changed the default config of awesome so that it *should* be able to find packages installed through LuaRocks. This commit added `pcall(require, "luarocks.loader")` to the beginning of the default config. Assuming awesome can find luarocks, this should make packages installed through luarocks available.
